name: 'Test'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pull-requests: read
  statuses: write

jobs:
  main:
    name: Execute Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - run: npm test
